export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_TRIP_MEMBER: 'NOT_TRIP_MEMBER',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  NOT_TRIP_OWNER: 'NOT_TRIP_OWNER',
  OWNER_CANNOT_LEAVE: 'OWNER_CANNOT_LEAVE',
  TRIP_NOT_FINISHED: 'TRIP_NOT_FINISHED',
  DIARY_PUBLISHED: 'DIARY_PUBLISHED',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  PARAGRAPH_FORBIDDEN: 'PARAGRAPH_FORBIDDEN'
} as const;
